scrape_configs:
  - job_name: 'jenkins'  # O nome do job de scrape no Prometheus.
    metrics_path: /jenkins/prometheus/  # O caminho onde o Prometheus buscará as métricas.
    scrape_interval: 15s  # O intervalo entre as coletas de métricas. Aqui, está configurado para 10 segundos.
    scrape_timeout: 5s  # O tempo máximo que o Prometheus aguardará pela resposta do Jenkins. Caso exceda, a coleta falhará.
    static_configs:
      - targets: ['172.18.0.4:8080']  # O endereço do Jenkins.
