services:

  grafana:
    container_name: grafana 
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - bridge

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "/home/paulo/Documentos/web-server/tomcat/Docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - bridge
  
networks:
  bridge:
    external: true